export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'

export const GET_DETAIL_PRODUCT_PENDING = 'GET_DETAIL_PRODUCT_PENDING'
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS'
export const GET_DETAIL_PRODUCT_ERROR = 'GET_DETAIL_PRODUCT_ERROR'

export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'


export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const CHECKOUT_PENDING = 'CHECKOUT_PENDING'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR'

export const ADD_BAG_PENDING = 'ADD_BAG_PENDING'
export const ADD_BAG_SUCCESS = 'ADD_BAG_SUCCESS'
export const ADD_BAG_ERROR = 'ADD_BAG_ERROR'

export const GET_BAG_PENDING = 'GET_BAG_PENDING'
export const GET_BAG_SUCCESS = 'GET_BAG_SUCCESS'
export const GET_BAG_ERROR = 'GET_BAG_ERROR'
