export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'

export const GET_DETAIL_PRODUCT_PENDING = 'GET_DETAIL_PRODUCT_PENDING'
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS'
export const GET_DETAIL_PRODUCT_ERROR = 'GET_DETAIL_PRODUCT_ERROR'

export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
