export { default as CustomerLogin } from './customer/login'
export { default as CustomerRegister } from './customer/register'
export { default as Home} from './Home'
export { default as Product} from './Product'
export { default as SellProduct} from './SellProduct'
export { default as MyBag} from './MyBag'
export { default as Profile} from './Profile'
export { default as Cart} from './Cart'
export { default as Category} from './Category'
export { default as Update} from './SellProduct/Update'